---
title: Exploratory data analysis
author: David Kane
tutorial:
  id: exploratory-data-analysis
output:
  learnr::tutorial:
    progressive: yes
    allow_skip: yes
runtime: shiny_prerendered
description: 'Tutorial for Chapter 11: Exploratory data analysis'
---

```{r setup, include = FALSE}
library(learnr)
library(tutorial.helpers)
library(tidyverse)

knitr::opts_chunk$set(echo = FALSE)
options(tutorial.exercise.timelimit = 60, 
        tutorial.storage = "local") 

```

```{r copy-code-chunk, child = system.file("child_documents/copy_button.Rmd", package = "tutorial.helpers")}
```

```{r info-section, child = system.file("child_documents/info_section.Rmd", package = "tutorial.helpers")}
```


<!-- The below links should be dropped at least once, if not twice. -->

<!-- https://ggplot2.tidyverse.org/ -->
<!-- https://ggplot2-book.org/ -->
<!-- https://socviz.co/ -->
<!-- https://clauswilke.com/dataviz/ -->

## Introduction
### 

This tutorial covers [Chapter 11: Exploratory data analysis](https://r4ds.hadley.nz/eda.html) from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund.  


## Summary
### 

This tutorial covered [Chapter 11: Exploratory data analysis](https://r4ds.hadley.nz/eda.html)  from [*R for Data Science (2e)*](https://r4ds.hadley.nz/) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund. 


```{r download-answers, child = system.file("child_documents/download_answers.Rmd", package = "tutorial.helpers")}
```
